export const FETCH_VENUES_REQUEST = "FETCH_VENUES_REQUEST";
export const FETCH_VENUES_SUCCESS = "FETCH_VENUES_SUCCESS";
export const FETCH_VENUES_FAILURE = "FETCH_VENUES_FAILURE";

export const FETCH_NEARBY_VENUES_REQUEST = "FETCH_NEARBY_VENUES_REQUEST";
export const FETCH_NEARBY_VENUES_SUCCESS = "FETCH_NEARBY_VENUES_SUCCESS";
export const FETCH_NEARBY_VENUES_FAILURE = "FETCH_NEARBY_VENUES_FAILURE";

export const SEARCH_VENUES_REQUEST = "SEARCH_VENUES_REQUEST";
export const SEARCH_VENUES_SUCCESS = "SEARCH_VENUES_SUCCESS";
export const SEARCH_VENUES_FAILURE = "SEARCH_VENUES_FAILURE";
